---
# tasks file for install_docker
- name: Install aptitude using apt9
  become: yes
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages
  become: yes
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  become: yes
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python
  become: yes
  pip:
    name: 
      - docker
      - docker-compose

- name: Add User to Group Docker
  command: sudo usermod -aG docker ${USER}